name: Semantic Release

on:
  workflow_dispatch:

jobs:
  semantic_release:
    name: 'Semantic Release'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - run: |
          sed -i -e s/REPLACEBASE64PAT/${{ secrets.GHB64 }}/g ./.npmrc
          sed -i -e s/REPLACEBASE64PAT/${{ secrets.GHB64 }}/g ./packages/app/.npmrc
          sed -i -e s/REPLACEBASE64PAT/${{ secrets.GHB64 }}/g ./packages/backend/.npmrc

      - name: Setup Github Packages Registry
        uses: actions/setup-node@v2.5.1
        with:
          registry-url: 'https://itsals.pkgs.visualstudio.com/_packaging/as.com-npm/npm/registry/'
          always-auth: true
          

      - name: Build Package
        run: |
          yarn install
          yarn tsc
          yarn build

      # - name: Semantic Release (Dry Run)
      #   if: ${{ github.ref != 'refs/heads/main'  }}
      #   run: |
      #     npm run release -- --dry-run --branches ${GITHUB_REF#refs/heads/}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.GH_TOKEN }}
      #     NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Run publish
        run: |
          git config user.name "ecomm-github-automtn"
          git config user.email "ecomm_github_automtn@alaskaair.com"
          lerna publish from-package --yes --no-verify-access